version: "{build}"
os: Visual Studio 2017
configuration: Debug
environment:
    COVERALLS_REPO_TOKEN: token
skip_branch_with_pr: true
build_script:
    - ps: >-
          ./build.ps1
artifacts:
    - path: "*.nupkg"
    - path: '.artifacts\**\*.nupkg'
      name: NuGet Packages
    - path: '.artifacts\**\*.snupkg'
      name: NuGet Symbol Packages
